// ============================================================
// ESLint Flat Config — CompoundIQ
// ============================================================
//
// Uses the native flat-config exports of eslint-config-next (16+).
// Previously this file used @eslint/eslintrc FlatCompat to wrap the
// legacy .eslintrc.json shape, which threw "Converting circular
// structure to JSON" on ESLint 9 because the shared configs had
// already been converted to flat configs internally — the compat
// layer was double-wrapping plugin objects that had circular refs.
//
// Fix: drop FlatCompat and import the flat configs directly. As of
// eslint-config-next@16.2.1 the package exports:
//   - eslint-config-next/core-web-vitals  (Core Web Vitals + Next)
//   - eslint-config-next/typescript       (typescript-eslint ruleset)
// Each export is already a flat config array ready to spread into
// the user config. No compat layer required.

import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

/** @type {import('eslint').Linter.Config[]} */
const config = [
  // Ignore build artifacts, vendored files, and generated DB types.
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'src/types/database.types.ts', // generated by `npm run db:types`
      'public/**',
    ],
  },

  // Next.js Core Web Vitals + Next-specific rules
  ...coreWebVitals,

  // typescript-eslint recommended + Next-specific TS rules
  ...typescript,

  // ── Transitional rule overrides ─────────────────────────────────
  // Some React 19 Compiler rules (set-state-in-effect, static-components,
  // purity) surface real pre-existing patterns that need careful refactor.
  // Downgrading to warnings keeps them visible without blocking CI while
  // the cleanup is tracked as a separate work item. Do NOT add new code
  // that violates these — the refactor PR will remove these overrides.
  // Backlog ticket: WO-TBD — "Refactor React 19 Compiler lint findings"
  {
    rules: {
      'react-hooks/set-state-in-effect':         'warn',
      'react-hooks/static-components':           'warn',
      'react-hooks/purity':                      'warn',
      // Suppressed until the backlog refactor PR addresses these 12 findings.
    },
  },

  // Per-file override for server components: Date.now() and other
  // "impure" calls during render are CORRECT in server components
  // (they run once per request, not per render). The React 19 Compiler
  // rules don't distinguish server vs client components.
  {
    files: ['src/app/**/page.tsx', 'src/app/**/layout.tsx', 'src/app/api/**/route.ts'],
    rules: {
      'react-hooks/purity': 'off',
    },
  },

  // ── WO-88: type-bypass guard for Stripe-touching files ───────────
  //
  // Catches the failure mode that broke PR #44 commit 3/3 at write-
  // time: an author casts through `unknown` or `any` to bypass the
  // SDK's type system, asserting a parameter exists when the SDK
  // doesn't expose it. The cast is the smoking-gun signal — if you
  // need to bypass types to land a third-party API parameter, the
  // parameter probably isn't real.
  //
  // Three patterns blocked:
  //   - `x as any`                       (full type-system escape)
  //   - `x as unknown` (or `as unknown as T`) (cast-through-unknown)
  //   - `x as Record<string, unknown>`   (the specific cast that broke
  //                                       PR #44 commit 3/3)
  //
  // Scope: ONLY files that make actual Stripe API calls or pass options
  // to Stripe Elements. NOT post-Stripe surfaces (e.g.,
  // `src/app/checkout/success/page.tsx` reads Supabase joined-query
  // results, not Stripe — Supabase shape-coercion casts there are out
  // of scope for this rule). Companion guards:
  //   - WO-89 PR-template doc-citation rule (PR #46, shipped) — forces
  //     reviewer-facing evidence at submission
  //   - WO-92 SDK type-check smoke (queued) — compile-time regression
  //     guard that this rule's blocked patterns can't be used to bypass
  //
  // Inline override allowed via `// eslint-disable-next-line` ONLY when
  // accompanied by a comment that includes the third-party API doc URL
  // (per CONTRIBUTING.md "Third-Party API Parameter Rule"). Reviewers
  // must reject any inline disable that lacks the doc citation.
  {
    files: [
      'src/lib/stripe/**',
      'src/app/api/checkout/payment-intent/**',
      'src/app/api/webhooks/stripe/**',
      'src/app/checkout/[token]/_components/**',
    ],
    ignores: [
      // Test files mock the Stripe SDK and use cast-through-unknown for fixture
      // construction (NextRequest mocks, etc.). The WO-88 failure mode doesn't
      // apply because mocked tests can't reach the live Stripe API.
      '**/__tests__/**',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "TSAsExpression > TSAnyKeyword",
          message:
            "WO-88: `as any` forbidden in Stripe-touching files. " +
            "If you're bypassing the SDK type system to land a third-party API parameter, " +
            "stop and check the docs — the parameter may not exist. See CONTRIBUTING.md " +
            "'Third-Party API Parameter Rule.'",
        },
        {
          selector: "TSAsExpression > TSUnknownKeyword",
          message:
            "WO-88: `as unknown` (cast through unknown) forbidden in Stripe-touching files. " +
            "This was the exact pattern that broke PR #44 commit 3/3 — author cast through " +
            "unknown to bypass SDK types, live API rejected the parameter, CI E2E broke. " +
            "See CONTRIBUTING.md 'Third-Party API Parameter Rule.'",
        },
        {
          selector:
            "TSAsExpression[typeAnnotation.type='TSTypeReference'][typeAnnotation.typeName.name='Record']",
          message:
            "WO-88: `as Record<string, unknown>` forbidden in Stripe-touching files. " +
            "This is the specific cast that shipped a non-existent Stripe parameter in PR #44 " +
            "commit 3/3. Quote the API doc URL + parameter in the PR description and use a " +
            "properly-typed SDK upgrade instead. See CONTRIBUTING.md 'Third-Party API Parameter Rule.'",
        },
      ],
    },
  },
]

export default config
